// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/accrual.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/iudanet/yp-diplom-1/internal/models"
)

// MockAccrualClientInterface is a mock of AccrualClientInterface interface.
type MockAccrualClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientInterfaceMockRecorder
}

// MockAccrualClientInterfaceMockRecorder is the mock recorder for MockAccrualClientInterface.
type MockAccrualClientInterfaceMockRecorder struct {
	mock *MockAccrualClientInterface
}

// NewMockAccrualClientInterface creates a new mock instance.
func NewMockAccrualClientInterface(ctrl *gomock.Controller) *MockAccrualClientInterface {
	mock := &MockAccrualClientInterface{ctrl: ctrl}
	mock.recorder = &MockAccrualClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClientInterface) EXPECT() *MockAccrualClientInterfaceMockRecorder {
	return m.recorder
}

// GetOrderAccrual mocks base method.
func (m *MockAccrualClientInterface) GetOrderAccrual(ctx context.Context, orderNumber string) (*models.OrderAccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(*models.OrderAccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderAccrual indicates an expected call of GetOrderAccrual.
func (mr *MockAccrualClientInterfaceMockRecorder) GetOrderAccrual(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderAccrual", reflect.TypeOf((*MockAccrualClientInterface)(nil).GetOrderAccrual), ctx, orderNumber)
}
