package handlers

import (
	"net/http"

	_ "github.com/iudanet/yp-diplom-1/internal/docs" // docs is generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

//	@title			Gophermart Loyalty System API
//	@version		1.0
//	@description	This is a Gophermart loyalty system API server.

//	@contact.name	API Support
//	@contact.url	http://www.swagger.io/support
//	@contact.email	support@swagger.io

//	@license.name	Apache 2.0
//	@license.url	http://www.apache.org/licenses/LICENSE-2.0.html

//	@host		localhost:8080
//	@BasePath	/
//	@schemes	http

//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization

func (s *Server) setupSwagger(mux *http.ServeMux) {
	mux.HandleFunc("GET /swagger/", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // URL pointing to API definition
	))
}
